export interface IPsychologist {
    name: string
    internal_number: any
    sex: any
    telegram_id: number
    allow_assignment: boolean
    min_client_age: number
    max_client_age: number
    link_photo: string
    link_video: any
    short_description: string
    anketa_name: any
    age: number
    experience: any
    client_sex: string
    works_with: string
    queries: string
    min_session_price: any
    max_session_price: any
    number_of_clients_provided: number
    debt: any
    id: string
    send_feedback: boolean
    send_payment_link: boolean
    subscription_payment_month: any
    in_community: boolean
    psychologist_contact: any
    main_modal: string
    additional_modals: []
    vk: string
    site: string
    telegram: string
    is_married: boolean
    has_children: boolean
    all_with_price: boolean
    first_free: boolean
    help_hand: boolean
    verified: boolean
    personal_therapy_duration: string
    personal_therapy_type: string
    is_onboarding_finished: boolean
} 